### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Jiankun-Huang** [peyton2465/Warp4Free#4]
How th do I inject the dll into the exe, why cant you just give a ready made exe?

**Comment by peyton2465** [comment]
These are my reasons for why I will not be releasing my own patched version of their binaries:
Reason 1: Parsec's binaries are all signed
Reason 2: I do not want to redistribute their software with my own modifications
Reason 3: Even if I were to redistribute their software, it would require a TON of work to patch their binaries to my liking.
Reason 4: I would need to update my patch each time they release a new update.

If you want to inject the DLL, I suggest using something like Extreme Injector or https://github.com/adamhlt/DLL-Injector

To use the latter, open your terminal (use powershell for minimal issues) as admin and run this command on the 64 bit version of the injector: 
*In a directory containing both Warp4Free.dll and inject.exe (64 bit)

.\inject.exe Warp4Free.dll parsecd.exe

You will need to do this on the host machine at least once to set up the host settings.
I suggest modifying your parsec shortcut to point to a batch file that will do this automatically when you run parsec.

**Comment by Jiankun-Huang** [comment]
Anyway to make the patch permanent, instead of injecting every time?

**Comment by Jiankun-Huang** [comment]
Sorry but how do I add the script to the shortcut? Thanks
