### ISSUE TITLE
Parsec 150-87c - Windows 11

### ISSUE THREAD

**Issue by F0x06** [peyton2465/Warp4Free#5]
Hi, i've injected the DLL inside my WIndows 11 vm, however the `4:4:4 Color` option is still grayed out, normal ? 

Since it uses addresses, maybe you tested with a different parsec version ? 

DLL output:
```
Warp4Free Attached
Module Base: 7fffe5e00000
UI Update: 7fffe5e75130
Hooked!
Arg 7 Address: 4389dff970
```

Thanks.

**Comment by peyton2465** [comment]
Hi there. I am currently on 150-87c but Windows 10 and it works fine. This may be an issue with Windows 11. What did you use to inject the dll into the parsec process? This is definitely something I'd like to figure out.

**Comment by F0x06** [comment]
> Hi there. I am currently on 150-87c but Windows 10 and it works fine. This may be an issue with Windows 11. What did you use to inject the dll into the parsec process? This is definitely something I'd like to figure out.

Hi, thanks for the reply, i used https://github.com/adamhlt/DLL-Injector as mentioned in https://github.com/peyton2465/Warp4Free/issues/4

Using this command line `Inject-x64.exe x64\Debug\Warp4Free.dll parsecd.exe`

**Comment by F0x06** [comment]
Hi, did you got any time to look at the issue ? Feel free to ask if i can help you.

**Comment by peyton2465** [comment]
Sorry but no I haven't done anything yet. I don't have windows 11 installed on anything so I'd need to set up a vm and I just haven't felt like it

**Comment by F0x06** [comment]
I just figured out the issue, in issue https://github.com/peyton2465/Warp4Free/issues/4 you wrote "**You will need to do this on the host machine at least once to set up the host settings**."

But the "Host" machine is the one you are connecting to technically right ? I just patched **parsecd** on my PC (The client machine) and it works now :)

**Comment by peyton2465** [comment]
Glad to hear you figured it out. Hopefully this will help others with similar issues
